### PR TITLE
Create .kube directory to enable caching

### LINKED ISSUE #30: failed to write cache due to mkdir /.kube: permission denied
**Description**
Since this container runs as a non-root user, it cannot create the /.kube directory, which is needed for kubectl to cache files.

This results in so many requests being sent to the apiserver that kubectl throttles itself:
```
I1130 00:26:16.420352      20 request.go:665] Waited for 1.191715678s due to client-side throttling, not priority and fairness, request: GET:https://10.20.0.1:443/apis/scheduling.k8s.io/v1?timeout=32s
```

**Steps to reproduce the issue:**

1. Create a cluster with many extra CRDs. I have 91. (unsure of the specific threshold to trigger throttling, or if this step is even required)
2. Run a bitnami-docker-kubectl container
3. Run any kubectl command, such as `kubectl get pods -v=6`

**Describe the results you received:**

The request takes a while and logs a warning that kubectl is throttling itself. The verbosity allows us to see the reason for the issue is the inability to create the /.kube folder:

```
I1130 00:28:49.733712      27 cached_discovery.go:87] failed to write cache to /.kube/cache/discovery/10.20.0.1_443/autoscaling/v1/serverresources.json due to mkdir /.kube: permission denied
```

**Describe the results you expected:**

No throttling, only one request is sent. As a workaround, you can pass --cache-dir=/tmp/.kube, which results in the desired result:
```
$ kubectl --cache-dir=/tmp/.kube get pod -v=6
I1130 00:30:15.637403      42 merged_client_builder.go:163] Using in-cluster namespace
I1130 00:30:15.637628      42 merged_client_builder.go:121] Using in-cluster configuration
I1130 00:30:15.720633      42 merged_client_builder.go:121] Using in-cluster configuration
I1130 00:30:15.827677      42 merged_client_builder.go:121] Using in-cluster configuration
I1130 00:30:15.941405      42 round_trippers.go:454] GET https://10.20.0.1:443/api/v1/namespaces/machaffe/pods?limit=500 200 OK in 24 milliseconds
NAME                     READY   STATUS    RESTARTS   AGE
debug-5ff988d744-h8wlm   1/1     Running   1          3h6m
```

A possible fix could involve just creating the /.kube folder with relaxed permissions at build-time. I don't think you can change the default cache dir aside from the --cache-dir flag.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:
n/a

- Output of `docker info`:
n/a

- Output of `docker-compose version` (if applicable):
n/a

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Kubernetes with kubespray and a bunch of addons. Gatekeeper requires one CRD per policy, so that's the biggest source of CRDs.

### PR DESCRIPTION
**Pull request by mac-chaffee**
**Description of the change**

Fixes #30 

**Benefits**

This change will significantly speed up subsequent kubectl invocations since it doesn't attempt to fill the cache every time. This is particularly important for clusters with many CRDs since at some point, kubectl will throttle itself if it sends too many requests.

**Possible drawbacks**
n/a

**Applicable issues**

#30 

**Additional information**

Tested:

```
$ docker build -t bitnami-docker-kubectl .
...
$ docker run -it --entrypoint=bash -v ~/.kube:/tmp/.kube bitnami-docker-kubectl
I have no name!@700c4b56cb48:/$ KUBECONFIG=/tmp/.kube/host-kubeconfig kubectl get pods -v=6
I1129 23:27:00.866816       8 loader.go:372] Config loaded from file:  /tmp/.kube/host-kubeconfig
I1129 23:27:00.896265       8 round_trippers.go:454] GET https://10.20.0.1:443/api?timeout=32s 200 OK in 28 milliseconds
I1129 23:27:00.906988       8 round_trippers.go:454] GET https://10.20.0.1:443/apis?timeout=32s 200 OK in 5 milliseconds
I1129 23:27:00.933871       8 round_trippers.go:454] GET https://10.20.0.1:443/apis/admissionregistration.k8s.io/v1?timeout=32s 200 OK in 16 milliseconds
I1129 23:27:00.935865       8 round_trippers.go:454] GET https://10.20.0.1:443/apis/authentication.k8s.io/v1beta1?timeout=32s 200 OK in 11 milliseconds
I1129 23:27:00.936779       8 round_trippers.go:454] GET https://10.20.0.1:443/apis/storage.k8s.io/v1beta1?timeout=32s 200 OK in 20 milliseconds
...
note that the cache is being populated
...
I1129 23:27:01.187932       8 round_trippers.go:454] GET https://10.20.0.1:443/api/v1/namespaces/machaffee/pods?limit=500 200 OK in 11 milliseconds
No resources found in machaffee namespace.

# Subsequent requests do not need to refill the cache:
I have no name!@700c4b56cb48:/$ KUBECONFIG=/tmp/.kube/kubeconfig-blackbalsam kubectl get pods -v=6
I1129 23:29:30.629332      14 loader.go:372] Config loaded from file:  /tmp/.kube/kubeconfig-blackbalsam
I1129 23:29:30.678900      14 round_trippers.go:454] GET https://10.20.0.1:443/api/v1/namespaces/machaffee/pods?limit=500 200 OK in 36 milliseconds
No resources found in machaffee namespace.
```

Overwriting /.kube with a volume mount also still works:
```
$ docker run -it --entrypoint=bash -v ~/.kube:/.kube bitnami-docker-kubectl
I have no name!@c25b608836a0:/$ KUBECONFIG=/.kube/kubeconfig-host kubectl get pods -v=6
I1129 23:30:24.488789      29 loader.go:372] Config loaded from file:  /.kube/kubeconfig-host
I1129 23:30:24.672132      29 round_trippers.go:454] GET https://10.20.0.1:443/api/v1/namespaces/machaffee/pods?limit=500 200 OK in 30 milliseconds
No resources found in machaffee namespace.
```

### CODE REVIEW

**Review by miguelaeh — COMMENTED** [review]
Hi @mac-chaffee ,
I don't see why this is needed.
If you mount a volume into `/.kube` with the proper permissions there is not need to create the folder.
And, if you don't mount a volume, then the cache won't be stored so it won't change anything.
Could you clarify that?

**Comment by mac-chaffee** [comment]
@miguelaeh One use-case is running the container inside of kubernetes itself using a service account token. In that situation, the credentials get mounted under /var/run, not in /.kube.

Saving the cache is important if someone runs a shell script inside the container that invokes kubectl multiple times. It's fine that the cache is thrown away when the container exits, but a complex shell script might invoke kubectl dozens of times (attempting to populate the cache every time) before exiting.

**Comment by miguelaeh** [comment]
Hi @mac-chaffee ,
>One use-case is running the container inside of kubernetes itself using a service account token. In that situation, the credentials get mounted under /var/run, not in /.kube.

In this case, why not just mount a volume into `/.kube` ? It shouldn't be necessary to create the directory in the image.

**Comment by mac-chaffee** [comment]
@miguelaeh mount an empty volume into /.kube in addition to the service account token?

I doubt people would think to do that. Remember that without the cache dir, all requests would just appear to be a little slow. Unless they have tons of CRDs like I do, they wouldn't see any errors or warnings, so they wouldn't think to investigate further.

What is the downside of this change in your view? I tested that it does not affect people who do mount volumes to /.kube, so it seems like you're just trying to save 1 line of code in the Dockerfile. There's already precedent for doing this: https://github.com/bitnami/bitnami-docker-express/blob/f33bcac5dbfbcd616bf75037a3565db638d2548b/4/debian-10/Dockerfile#L24

**Review by miguelaeh — APPROVED** [review]
Hi @mac-chaffee ,
It is not that this PR has any downside or saving the Dockerfile line, I will accept it.
I just wanted to understand in which situation is this change needed since the directory will be created by your volume at mount time.

**Pull request merged**
