### PR TITLE
Xzx

### PR DESCRIPTION
**Pull request by Bariscankibarcekici**
**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

**Additional information**

### CODE REVIEW

**Comment by carrodher** [comment]
Hi, please note those changes are not correct nor add any value to the container image.
We detected similar changes in the past, see
https://github.com/bitnami/bitnami-docker-kubectl/pull/45
https://github.com/bitnami/bitnami-docker-kubectl/pull/48
https://github.com/bitnami/bitnami-docker-kubectl/pull/49
https://github.com/bitnami/bitnami-docker-kubectl/pull/50

Please, if you would like to contribute you should follow the [CONTRIBUTING guidelines](https://github.com/bitnami/bitnami-docker-kubectl/blob/master/CONTRIBUTING.md), otherwise, we will close the different PRs and, in case the issue persists, take a different action in order to avoid those unnecessary and disturbing PRs

**Comment by Bariscankibarcekici** [comment]
open pls

**Comment by carrodher** [comment]
If you would like to contribute you should follow the [CONTRIBUTING guidelines](https://github.com/bitnami/bitnami-docker-kubectl/blob/master/CONTRIBUTING.md), otherwise, we will close the different PRs and, in case the issue persists, take a different action in order to avoid those unnecessary and disturbing PRs

**Comment by Bariscankibarcekici** [comment]
xzx

**Review by Bariscankibarcekici — COMMENTED** [review]
I want to revert pls

**Review by Bariscankibarcekici — COMMENTED** [review]
I want to revert google.yml

**Pull request closed without merging**
